server {
  listen 8084;

  location /api/ {
    proxy_pass http://127.0.0.1:8090/;
    client_max_body_size 1000m;
    client_body_buffer_size 500m;
  }

  location /admin/ {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /admin/index.html;
  }

  location = /admin {
    return 301 /admin/;
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root html;
  }
}
