version: '3.1'
services:
  tangsengdaodaoserver:
    image: registry.cn-shanghai.aliyuncs.com/wukongim/tangsengdaodaoserver:latest
    restart: always
    command: "api"
    ports:
      - "8090:8090"
    volumes:
      - ./tsdddata:/home/data
      - ./tsddlogs:/home/logs
    depends_on:
      - redis
      - mysql
    environment:
      - TZ=Asia/Shanghai
    networks:
      - fullstack_default

networks:
  fullstack_default:
    external: true
